# Generated by Django 6.0 on 2026-02-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(default='EDICION', max_length=30)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IngresoPlayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('tipo_vehiculo', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vehículo')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(null=True, verbose_name='Año')),
                ('color', models.CharField(max_length=30)),
                ('nro_legajo_playon', models.CharField(max_length=30, unique=True, verbose_name='N° de legajo en playón')),
                ('lugar_infraccion', models.CharField(max_length=255, verbose_name='Lugar de la infracción')),
                ('acta_infraccion_recibida', models.BooleanField(default=False, verbose_name='Acta de infracción recibida')),
                ('acta_secuestro_recibida', models.BooleanField(default=False, verbose_name='Acta de secuestro recibida')),
                ('inventario_objetos_visibles_recibido', models.BooleanField(default=False, verbose_name='Inventario de objetos visibles recibido')),
                ('registro_fotografico_recibido', models.BooleanField(default=False, verbose_name='Registro fotográfico recibido')),
                ('prueba_alcoholemia_estado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NC', 'No corresponde')], default='NC', max_length=2, verbose_name='Prueba de alcoholemia/test')),
                ('coincide_inventario', models.BooleanField(default=False, verbose_name='¿Coincide el inventario?')),
                ('coinciden_danios_registrados', models.BooleanField(default=False, verbose_name='¿Coinciden daños registrados?')),
                ('detalle_danios_no_coincidentes', models.TextField(blank=True, verbose_name='Detalle de daños no coincidentes')),
                ('bateria_desconectada', models.BooleanField(default=False, verbose_name='Batería desconectada')),
                ('ubicacion_interna', models.CharField(max_length=100, verbose_name='Ubicación interna en playa')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('retirado', models.BooleanField(default=False, verbose_name='¿Retirado?')),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('nombre_retira', models.CharField(blank=True, max_length=100, verbose_name='Nombre de quien retira')),
                ('dni_retira', models.CharField(blank=True, max_length=20, verbose_name='DNI de quien retira')),
                ('observaciones_egreso', models.TextField(blank=True, verbose_name='Observaciones de egreso')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_entregados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso al playón',
                'verbose_name_plural': 'Ingresos al playón',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
