# Generated by Django 6.0 on 2026-02-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        ('playon', '0001_initial'),
        ('vehiculos', '0008_remove_ingresoplayon_entregado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoplayon',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='playon.lugarplayon'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='auditoriaingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_ingresos', to='ingresos.ingresoplayon'),
        ),
    ]
