# Generated by Django 6.0 on 2026-02-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='ingresos.ingresoplayon'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='ubicacion_interna',
            field=models.CharField(max_length=100, verbose_name='Ubicación interna en playón'),
        ),
    ]
