# Generated by Django 6.0 on 2026-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_alter_auditoriaingreso_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoplayon',
            name='operador_grua',
            field=models.TextField(blank=True, default='', verbose_name='Operador de grúa y detalles del traslado'),
        ),
    ]
