# Generated by Django 6.0 on 2026-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_ingresoplayon_operador_grua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoplayon',
            name='observaciones_generales',
            field=models.TextField(blank=True, default='-', verbose_name='Observaciones generales'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='operador_grua',
            field=models.TextField(default='-', verbose_name='Operador de grúa y detalles del traslado'),
        ),
    ]
