# Generated by Django 6.0 on 2026-02-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_alter_ingresoplayon_observaciones_generales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoplayon',
            name='retiro_autorizado',
            field=models.BooleanField(default=False, verbose_name='Retiro autorizado por Juzgado'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='retiro_autorizado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='retiro_autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retiros_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='observaciones_generales',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones generales'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='operador_grua',
            field=models.TextField(default='', verbose_name='Operador de grúa y detalles del traslado'),
        ),
    ]
