# Generated by Django 6.0 on 2026-02-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0006_ingresoplayon_retiro_autorizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaingreso',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RenameField(
            model_name='auditoriaingreso',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='retiro_autorizado',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='retiro_autorizado_en',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='retiro_autorizado_por',
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado por Juzgado'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='juzgado/oficios/', verbose_name='Oficio / archivo'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha bloqueo'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo del bloqueo'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos_playon', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='fecha_secuestro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de secuestro'),
        ),
        migrations.AlterField(
            model_name='auditoriaingreso',
            name='accion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriaingreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga'),
        ),
    ]
