# Generated by Django 6.0 on 2026-02-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0007_alter_auditoriaingreso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_archivo',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_en',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_motivo',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bloqueo_juzgado_por',
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='oficio_juez_archivo',
            field=models.FileField(blank=True, null=True, upload_to='retiros/oficios/', verbose_name='Oficio del Juzgado (archivo)'),
        ),
        migrations.AlterField(
            model_name='auditoriaingreso',
            name='accion',
            field=models.CharField(default='EDICION', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriaingreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_ingresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
