# Generated by Django 5.1 on 2026-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0008_remove_ingresoplayon_bloqueo_juzgado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoplayon',
            name='observaciones_generales_interno',
            field=models.TextField(blank=True, verbose_name='Observaciones generales internas'),
        ),
    ]
