# Generated by Django 6.0 on 2026-02-02 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_acta', models.CharField(max_length=30, unique=True, verbose_name='N° de acta')),
                ('dni_infractor', models.CharField(max_length=20, verbose_name='DNI')),
                ('nombre_infractor', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido_infractor', models.CharField(max_length=80, verbose_name='Apellido')),
                ('dominio', models.CharField(max_length=10, verbose_name='Dominio (patente)')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('es_titular', models.BooleanField(default=False, verbose_name='¿Es titular?')),
                ('nro_cedula', models.CharField(blank=True, max_length=50, verbose_name='N° de cédula')),
                ('retenido_playon', models.BooleanField(default=False, verbose_name='¿Retenido para playón de secuestro?')),
                ('descripcion', models.TextField(verbose_name='Descripción / tipo de infracción')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_infraccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
