# Generated by Django 6.0 on 2026-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0002_auditoriainfraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='prueba_alcoholemia_estado',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NC', 'No corresponde')], default='NC', max_length=2, verbose_name='Prueba de alcoholemia/test'),
        ),
    ]
