# Generated by Django 6.0 on 2026-02-25 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0003_infraccion_prueba_alcoholemia_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='infracciones/adjuntos/', verbose_name='Archivo adjunto (foto o PDF)'),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='fecha_acta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del acta'),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='inspector_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas_infraccion_autor', to=settings.AUTH_USER_MODEL, verbose_name='Inspector responsable/autor'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_infraccion', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
        migrations.DeleteModel(
            name='AuditoriaInfraccion',
        ),
    ]
