# Generated by Django 6.0 on 2026-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0005_auditoriainfraccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='inspector_autor',
        ),
        migrations.AddField(
            model_name='infraccion',
            name='autor_acta',
            field=models.CharField(blank=True, max_length=120, verbose_name='Inspector responsable / Autor del acta'),
        ),
    ]
