# Generated by Django 5.1 on 2026-04-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0006_remove_infraccion_inspector_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='autor_acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_autor', to=settings.AUTH_USER_MODEL, verbose_name='Inspector responsable / Autor del acta'),
        ),
    ]
