# Generated by Django 5.1 on 2026-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0007_alter_infraccion_autor_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='autor_acta',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Inspector responsable / Autor del acta'),
        ),
    ]
