# Generated by Django 6.0 on 2025-12-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=10, unique=True, verbose_name='Dominio (Patente)')),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('nro_chasis', models.CharField(blank=True, max_length=50, verbose_name='N° de chasis')),
                ('nro_motor', models.CharField(blank=True, max_length=50, verbose_name='N° de motor')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta en sistema')),
            ],
        ),
    ]
