# Generated by Django 6.0 on 2025-12-11 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPlayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vehículo')),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30)),
                ('nro_legajo_playon', models.CharField(max_length=30, unique=True, verbose_name='N° de legajo en playón')),
                ('lugar_infraccion', models.CharField(blank=True, max_length=255, verbose_name='Lugar de la infracción')),
                ('acta_infraccion_recibida', models.BooleanField(default=False, verbose_name='Acta de infracción recibida')),
                ('acta_secuestro_recibida', models.BooleanField(default=False, verbose_name='Acta de secuestro recibida')),
                ('inventario_objetos_visibles_recibido', models.BooleanField(default=False, verbose_name='Inventario de objetos visibles recibido')),
                ('registro_fotografico_recibido', models.BooleanField(default=False, verbose_name='Registro fotográfico recibido')),
                ('prueba_alcoholemia_estado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NC', 'No corresponde')], default='NC', max_length=2, verbose_name='Prueba de alcoholemia/test')),
                ('coincide_inventario', models.BooleanField(default=True, verbose_name='¿Coincide el inventario?')),
                ('coinciden_danios_registrados', models.BooleanField(default=True, verbose_name='¿Coinciden los daños registrados?')),
                ('detalle_danios_no_coincidentes', models.TextField(blank=True, verbose_name='Detalle de daños no coincidentes')),
                ('bateria_desconectada', models.BooleanField(default=False, verbose_name='Batería desconectada')),
                ('ubicacion_interna', models.CharField(blank=True, max_length=100, verbose_name='Ubicación interna en playa')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Ingreso al playón',
                'verbose_name_plural': 'Ingresos al playón',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
