# Generated by Django 6.0 on 2025-12-11 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_ingresoplayon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoplayon',
            name='dni_retira',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI de quien retira'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='nombre_retira',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de quien retira'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='observaciones_egreso',
            field=models.TextField(blank=True, verbose_name='Observaciones de egreso'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='retirado',
            field=models.BooleanField(default=False, verbose_name='¿Retirado?'),
        ),
    ]
