# Generated by Django 6.0 on 2025-12-15 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_ingresoplayon_dni_retira_ingresoplayon_entregado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresoplayon',
            options={'ordering': ['-fecha_ingreso']},
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='acta_infraccion_recibida',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='acta_secuestro_recibida',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='bateria_desconectada',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='coincide_inventario',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='coinciden_danios_registrados',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='detalle_danios_no_coincidentes',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='inventario_objetos_visibles_recibido',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='lugar_infraccion',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='observaciones_generales',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='prueba_alcoholemia_estado',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='registro_fotografico_recibido',
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='nro_legajo_playon',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LugarPlayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=1)),
                ('columna', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('FUERA', 'Fuera de servicio')], default='LIBRE', max_length=10)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('MOTO', 'Exclusivo motos')], default='GENERAL', max_length=10)),
            ],
            options={
                'ordering': ['fila', 'columna'],
                'unique_together': {('fila', 'columna')},
            },
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='vehiculos.lugarplayon'),
        ),
        migrations.CreateModel(
            name='MovimientoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='vehiculos.ingresoplayon')),
                ('lugar_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehiculos.lugarplayon')),
                ('lugar_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehiculos.lugarplayon')),
                ('movido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
