# Generated by Django 6.0 on 2025-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_ingresoplayon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresoplayon',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Ingreso al playón', 'verbose_name_plural': 'Ingresos al playón'},
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='acta_infraccion_recibida',
            field=models.BooleanField(default=False, verbose_name='Acta de infracción recibida'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='acta_secuestro_recibida',
            field=models.BooleanField(default=False, verbose_name='Acta de secuestro recibida'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='bateria_desconectada',
            field=models.BooleanField(default=False, verbose_name='Batería desconectada'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='coincide_inventario',
            field=models.BooleanField(default=True, verbose_name='¿Coincide el inventario?'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='coinciden_danios_registrados',
            field=models.BooleanField(default=True, verbose_name='¿Coinciden los daños registrados?'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='detalle_danios_no_coincidentes',
            field=models.TextField(blank=True, verbose_name='Detalle de daños no coincidentes'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='inventario_objetos_visibles_recibido',
            field=models.BooleanField(default=False, verbose_name='Inventario de objetos visibles recibido'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='lugar_infraccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lugar de la infracción'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='observaciones_generales',
            field=models.TextField(blank=True, verbose_name='Observaciones generales'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='prueba_alcoholemia_estado',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NC', 'No corresponde')], default='NC', max_length=2, verbose_name='Prueba de alcoholemia/test'),
        ),
        migrations.AddField(
            model_name='ingresoplayon',
            name='registro_fotografico_recibido',
            field=models.BooleanField(default=False, verbose_name='Registro fotográfico recibido'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='nro_legajo_playon',
            field=models.CharField(max_length=30, unique=True, verbose_name='N° de legajo en playón'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta en sistema'),
        ),
    ]
