# Generated by Django 6.0 on 2026-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_auditoriaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoplayon',
            name='anio',
            field=models.PositiveIntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='coincide_inventario',
            field=models.BooleanField(default=False, verbose_name='¿Coincide el inventario?'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='coinciden_danios_registrados',
            field=models.BooleanField(default=False, verbose_name='¿Coinciden los daños registrados?'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='lugar_infraccion',
            field=models.CharField(max_length=255, verbose_name='Lugar de la infracción'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='ingresoplayon',
            name='ubicacion_interna',
            field=models.CharField(max_length=100, verbose_name='Ubicación interna en playa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(max_length=50, verbose_name='N° de chasis'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nro_motor',
            field=models.CharField(max_length=50, verbose_name='N° de motor'),
        ),
    ]
