# Generated by Django 6.0 on 2026-02-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_alter_ingresoplayon_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='entregado_por',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='recibido_por',
        ),
        migrations.RemoveField(
            model_name='ingresoplayon',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='movimientolugar',
            name='ingreso',
        ),
        migrations.AlterUniqueTogether(
            name='lugarplayon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='movimientolugar',
            name='lugar_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientolugar',
            name='lugar_nuevo',
        ),
        migrations.RemoveField(
            model_name='movimientolugar',
            name='movido_por',
        ),
        migrations.DeleteModel(
            name='AuditoriaIngreso',
        ),
        migrations.DeleteModel(
            name='IngresoPlayon',
        ),
        migrations.DeleteModel(
            name='LugarPlayon',
        ),
        migrations.DeleteModel(
            name='MovimientoLugar',
        ),
    ]
