# Generated by Django 6.0 on 2026-02-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarPlayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=1)),
                ('columna', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('FUERA', 'Fuera de servicio')], default='LIBRE', max_length=10)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('MOTO', 'Exclusivo motos')], default='GENERAL', max_length=10)),
            ],
            options={
                'ordering': ['fila', 'columna'],
                'unique_together': {('fila', 'columna')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ingresos.ingresoplayon')),
                ('lugar_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='playon.lugarplayon')),
                ('lugar_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='playon.lugarplayon')),
                ('movido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
